services:
  - type: web
    name: laravel-chat
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
      - key: BROADCAST_CONNECTION
        value: reverb
      - key: REVERB_APP_ID
        value: 419271
      - key: REVERB_APP_KEY
        value: pp427mmqvd8gzpwlucjv
      - key: REVERB_APP_SECRET
        value: zudifarllhucguinfmty
      - key: REVERB_HOST
        value: 0.0.0.0
      - key: REVERB_PORT
        value: 8080
      - key: REVERB_SCHEME
        value: http